feat: ability to push from PRs
nvim-neorocks/luarocks-tag-release pull request #36
Opened 2023-03-13 22:07 UTC by teto

test

2023-03-13 22:30 UTC, teto commented on action.yml
> +    env:
I still dont understand how those people thought editing yaml would be a good idea, what I want to do is so simple yet the yaml syntax makes it so hard. I amn trying to debug this locally, Do you know how ? https://github.com/nektos/act ? how do you debug your GH actions

2023-03-13 22:41 UTC, mrcjkb commented on action.yml
> +    env:
I've tried act, but couldn't get it to work with this action (I never tried the full setup though).

So far, I've been going the tedious way of testing runs on GitHub on a test branch.

[This plugin](https://github.com/b0o/SchemaStore.nvim) along with yamlls might be helpful with the `action.yml`.

2023-03-13 22:48 UTC, teto commented on action.yml
> +    env:
What I tend to do for CIs is to bypass as much as possible their yaml code to put everything into shell scripts/Makefiles I can test locally. In this case I am tempted to add the code to adapt the name in the entrypoint.sh. What do you think ?

2023-03-14 06:33 UTC, mrcjkb commented on action.yml
> +    env:
You can do that in the `bin/luarocks-tag-release.lua` script:

```lua
local is_test_run = os.getenv('GITHUB_EVENT_NAME') == 'pull_request'
local package_name_suffix = is_test_run and '.testupload' or ''
```

And then you can use `is_test_run` to add `--dev` to the install options.

In a follow-up PR, I might split the lua script into separate modules/packages:
* A `bin` that parses the script arguments from the Github action's inputs and the Github CI environment.
* A `bin` that uses ArgParse for local debugging.
* A shared `lib` for the release logic.

2023-03-19 16:39 UTC, mrcjkb commented on action.yml
> +      if: {{github.event_name}} == 'pull_request'
This will cause the `run` to be skipped if it's not a PR.
I would just check for the environment variable in `bin/luarocks-tag-release-action.lua`.

2023-05-14 16:16 UTC, mrcjkb requested changes

2023-05-14 16:16 UTC, mrcjkb commented on lua/luarocks-tag-release.lua
> +---@param specrev number the version of the rockspec
```suggestion
---@param specrev string the version of the rockspec
```

2023-05-14 16:16 UTC, mrcjkb commented on lua/luarocks-tag-release.lua
> +  local target_rockspec_file = package_name .. '-' .. modrev .. '-' .. tostring(specrev) .. '.rockspec'
```suggestion
  local target_rockspec_file = package_name .. '-' .. modrev .. '-' .. specrev .. '.rockspec'
```

2023-07-16 20:53 UTC, teto commented
I close. Most of this has been merged and while I would love to be able to test the upload, it requires some changes on luarocks website first most likely. I will work on that and reopen when that becomes possible

2023-07-16 20:53 UTC, closed without merging